name: Update Commit Badge

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  commit-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository list
        id: list-repos
        run: |
          REPOS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/users/MattEzekiel/repos?type=all&visibility=all" | jq -r '.[] | .full_name')
          echo "::set-output name=repos::$REPOS"

      - name: Loop through repositories
        run: |
          total_commits=0
          for repo in ${{ steps.list-repos.outputs.repos }}; do
            echo "Fetching commits for $repo"
            commits=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$repo/commits" | jq 'length')
            total_commits=$((total_commits + commits))
          done
          echo "::set-output name=total_commits::$total_commits"

      - name: Generate commit badge
        run: |
          TOTAL_COMMITS="${{ steps.commit-badge.outputs.total_commits }}"
          echo '{"schemaVersion": 1, "label": "commits", "message": "'"$TOTAL_COMMITS"' commits total", "color": "blue"}' > commit-badge.json

      - name: Commit and push commit badge update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add commit-badge.json
          git commit -m "Update commit badge"
          git push
