name: Count Commits

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  count-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install puppeteer@10

      - name: Run scraper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node scraper.js

      - name: Generate commit badge
        run: |
          TOTAL_COMMITS=$(node scraper.js)
          echo "Commits: $TOTAL_COMMITS"
          echo '{"schemaVersion": 1, "label": "commits", "message": "'"$TOTAL_COMMITS"' commits", "color": "blue"}' > commit-count-badge.json

      - name: Upload badge
        uses: actions/upload-artifact@v2
        with:
          name: commit-badge
          path: commit-count-badge.json

      - name: Commit and push badge update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add commit-count-badge.json
          git commit -m "Update commit badge"
          git push
