name: Count Commits

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  count-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get repository list
        id: list-repos
        run: |
          REPOS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/users/MattEzekiel/repos?type=all&visibility=all" | jq -r '.[] | .full_name')
          echo "REPOS=$REPOS"
          REPOS_LIST=$(echo "$REPOS" | tr '\n' ' ')
          echo "REPOS_LIST=$REPOS_LIST" >> $GITHUB_ENV

      - name: Loop through repositories
        run: |
          total_commits=0
          for repo in $REPOS_LIST; do
            echo "Fetching commit activity for $repo"
            activity=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$repo/stats/contributors")
            echo "Activity response: $activity"
            commits=$(echo $activity | jq 'map(select(.author.login == "MattEzekiel")) | .[].total // 0' | jq -s 'add')
            if [ "$commits" = "null" ]; then
              commits=0
            fi
            echo "Commits: $commits"
            total_commits=$((total_commits + commits))
          done
          echo "TOTAL_COMMITS=$total_commits" >> $GITHUB_ENV

      - name: Generate commit badge
        run: |
          TOTAL_COMMITS=$(echo "${{ env.TOTAL_COMMITS }}")
          echo "Commits: $TOTAL_COMMITS"
          echo '{"schemaVersion": 1, "label": "commits", "message": "'"$TOTAL_COMMITS"' commits", "color": "blue"}' > commit-count-badge.json

      - name: Upload badge
        uses: actions/upload-artifact@v3
        with:
          name: commit-badge
          path: commit-count-badge.json

      - name: Commit and push badge update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add commit-count-badge.json
          git commit -m "Update commit badge"
          git push
